-- Fieldkit runtime switches. tools/build.py --install rewrites this file in the game folder
-- (Version, Tames.MountClasses from D_AISetup, FeatureConfig.tameregen.RegenTalents from
-- D_Talents); the repo copy is the shipped default. Keys deep-merge into the CONFIG table in
-- main.lua; FeatureConfig.<feature> merges into that feature's own CONFIG.
--
-- Core:
--   Features             list of feature ids to load (Scripts/features/<id>.lua)
--   CustomWorldSettings  false ignores the in-game rows and runs on the defaults here (default true)
--   Debug                log registrations and feature start/stop to UE4SS.log (default true)
--
-- FeatureConfig.tameregen (in game: Escape -> Custom World Settings -> Creatures wins over these):
--   PercentPerSecond     % of max health per second at Nurtured Recovery rank 4 when the prospect
--                        has no rate row applied yet (default 0.25; the in-game row is per minute, 15 = 0.25 %/s)
--   CombatGraceSeconds   seconds without damage or a target before healing resumes (default 10)
--   RequireFollow        false heals tames in every movement mode (default true)
--   HealWhileRidden      false pauses healing while someone rides the mount (default true)
--   TalentScaling        "reward" = rank's talent bonus / top rank's bonus (8/25/50/100 %),
--                        "rank" = rank / 4 (default "reward"); rank 4 is always the full rate
--   NoTalentFraction     share of the rate for a tame without the talent (default 0 = game regen only)
--
-- FeatureConfig.stow (in game: Escape -> Custom World Settings -> Misc wins over these):
--   RangeMetres          deposit range when the prospect has no range row applied (default 30)
--   Learn                opening a chest adds its contents to its pins (default true)
--   Keys                 { Deposit = { Key = "E", Modifiers = { "SHIFT" } }, Pin = { Key = "P", Modifiers = { "SHIFT" } } }
--                        UE4SS key names (F8, HOME, NUM_ZERO, ...) and modifiers SHIFT / CONTROL / ALT
--   TitleBar             show the pins in the chest window title (default true)
--   PinButton            add a "Pin contents" button to the chest window (default true)
--   Tooltip              show the pins in the in-world tooltip when looking at a chest (default true)
--   ExcludedContainers   container class names the deposit never fills, e.g. { "BP_Deep_Freeze_C" } (default none)
--   ItemNames            item row -> display name; written by build.py from D_ItemsStatic/D_Itemable
-- Pins are saved per prospect in <ue4ss>/FieldkitData/stow/<prospect id>.lua (outside the mod
-- folder, so reinstalling keeps them; delete a file to forget that prospect's pins).
--
-- FeatureConfig.scour (in game: Escape -> Custom World Settings -> Misc wins over these):
--   IntervalSeconds      seconds between pulses when the prospect has no interval row (default 180)
--   RadiusMetres         pulse reach when the prospect has no range row (default 25)
--   PiecesPerCartridge   building pieces one cartridge clears per pulse, per type (default 10)
--   MinAmount            build-up below this is ignored (default 0.05)
--   SampleSeconds        how often a scourer re-reads the build-up on its pieces (default 20)
--   QuietSeconds         a piece is cleared once its build-up has not grown for this long (default 60)
--   GrowthTolerance      growth below this between samples counts as not growing (default 0.002)
--   RequirePower / RequireCartridge   switch a cost off (default true; a --dev build sets DevMode)
--   DevMode              written by build.py: true on a --dev build = no power, no cartridges
--   Types                { [enum value] = { name, cartridge row } }; `fieldkit scour probe` shows the raw values
return {
    Version = "dev",
}
